### ISSUE TITLE
#ERROR!

### ISSUE THREAD

**Issue by Alin36** [pffy/googledocs-addon-hanyupinyin#9]
Hi! 

Thank you for the awesome plugin! It is extremely helpful! 

Lately I have been getting a lot of #ERROR! than before. I was editing the document and all of sudden almost all the cell content turned into #ERROR! Reloading didn't help. 

Is this something you might be able to fix/improve upon?

Thank you. 

![error hanyu pinyin](https://cloud.githubusercontent.com/assets/12693672/7910069/31aa53fe-0806-11e5-8f5e-2ddf92f52993.png)

**Comment by pffy** [comment]
@Alin36 Thank you for reporting this issue. We are also experiencing the same issues from time to time. We are looking into this issue.

**Comment by pffy** [comment]
An alternative API should be added to mitigate this. Use the IMPORTDATA function with a URL endpoint: https://support.google.com/docs/answer/3093335
--QA

**Comment by pffy** [comment]
We will implement both mitigation of Apps Script internals and the API endpoint.

**Comment by pffy** [comment]
@Alin36 Hello, we have just pushed out **HanyuPinyinTools version 10**, which may work a little better. Please let us know. You can find it in the Chrome Web Store.

**Comment by pffy** [comment]
@Alin36 We have also introduced a HanyuPinyin API: https://pinyintxt.appspot.com/

**It is designed for Google Sheets.**  To convert Chinese characters in **Cell A1**, use the following formula: `=IMPORTDATA("http://pinyintxt.appspot.com/hp/" & A1 )`

We now have streamlined the script load and added a backup web API.
Hope this helps, closing this issue.

If you have any problem, we can re-open this issue.
